# Generated by Django 2.0 on 2018-01-06 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_project_bim_server_roid'),
        ('monitor', '0004_auto_20180105_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimcomponent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Project'),
        ),
        migrations.AlterField(
            model_name='sensordatahist',
            name='isBadNotes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
