# Generated by Django 2.0 on 2017-12-18 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_permissions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userWrapper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='bim_server_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bim_server_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bim_server_username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_permissions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprojectrelation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Project'),
        ),
        migrations.AddField(
            model_name='userprojectrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.UserWrapper'),
        ),
    ]
