# Generated by Django 2.0 on 2017-12-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171219_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bim_server_poid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bim_server_port',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
