# Generated by Django 2.0 on 2018-01-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20171220_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bim_server_roid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
