# Generated by Django 2.0 on 2018-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_project_bim_server_roid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sensor_data_update_interval_ms',
            field=models.IntegerField(null=True),
        ),
    ]
